<?php

/**
 * @file
 * Install, update and uninstall functions for the alt_login module.
 */

/**
* Implementation of hook_schema().
*/
function alt_login_schema() {

  $schema['alt_login'] = array(
    'description' => 'Storage table for alternate user login names.',
    'fields' => array(
      'uid' => array(
        'description' => 'The uid of the user.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'alt_login' => array(
        'description' => 'The alternate login name for the user.',
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
        'default' => '',
      ),
    ),
    'primary key' => array('uid'),
    'foreign keys' => array(
      'uid' => array('user' => 'uid'),
    ),
  );

  return $schema;
}

/**
 * Move variables to config.
 */
function alt_login_update_1000() {
  $config = config('alt_login.settings');
  $config->set('user_registration', update_variable_get('alt_login_user_registration'));
  $config->save();
  update_variable_del('alt_login_user_registration');
}
